### PR TITLE
Ensure no newline in swift code example.

### PR DESCRIPTION
**Pull request by Insti**
Here's another one for you to cherry-pick.

### CODE REVIEW

**Comment by Insti** [comment]
Do you think it would be useful to convert the tests into Approvals so we test the whole html output at once?

**Comment by k3rni** [comment]
One gripe I have with approvals as they are now is that they don't show diffs on failing. 

Also, approvals always chomp off the trailing end line when comparing ([see here](https://github.com/kytrinyx/approvals/blob/master/lib/approvals/approval.rb#L69)). If we want to specify the endline conditions exactly, we probably should stick to regular comparison.

**Comment by k3rni** [comment]
Merged via cherry-pick in ea4ede6

**Comment by Insti** [comment]
> Also, approvals always chomp off the trailing end line when comparing (see here). If we want to specify the endline conditions exactly, we probably should stick to regular comparison.

That's not such a big deal when we're just comparing the html output, but I agree it's not a good thing in general, and about the lack of diffs, so I'm fine with sticking to the current tests for now.

**Comment by Insti** [comment]
Do you want to put together a PR for this?

It can either be a 'roll forward' PR in which case it might need some work to rebase it to the current master and I'll delete #3056, or you can do it as it is and mention that it depends on #3056 being applied first.

(One that depends on #3056 is probably safest in case Katrina merges it in the meantime but it's probably not big deal either way.)

**Comment by Insti** [comment]
OK, looks like #3056 got merged.
So the thing to do is delete #3058 and add a PR for the new changes we've made.

**Pull request closed without merging**
